name: Build

on:
  workflow_call:
#  push:
#    branches:
#      - qualif-foo
#      - qualif-bar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: simulate build
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          DEPLOY_URL:   ${{ secrets.DEPLOY_URL   }}
        run: |
          echo "build !"
          ! printenv | grep ^DEPLOY_
#        shell: python
#        run: |
#          import secrets
#          import sys
#          code = secrets.randbelow(2)
#          print("failure" if code else "success")
#          sys.exit(code)
